#!/bin/bash
set -o errexit -o nounset -o pipefail

function -h {
cat <<USAGE
 USAGE: mesosflexinstall (--rel <mesos-version>)?
                         (--slave-hostname <SLAVE_HOSTNAME>)?

  Install and configure Mesos with Zookeeper support.

USAGE
}; function --help { -h ;}


function main {
  options "$@"
  install_mesos
  configure_slave
}

function globals {
  export LC_ALL=en_US.UTF-8
}; globals

# Calls a function of the same name for each needed variable.
function global {
  for arg in "$@"
  do [[ ${!arg+isset} ]] || eval "$arg="'"$('"$arg"')"'
  done
}

function options {
  while [[ ${1:+isset} ]]
  do
    case "$1" in
      --rel)            rel="$2"                 ; shift ;;
      --slave-hostname) slave_hostname="$2"      ; shift ;; # See: MESOS-825
      --*)              err "No such option: $1" ;;
    esac
    shift
  done
}

function install_mesos {
  global os_release
  #case "$os_release" in
  #  ubuntu/14.04)      install_with_apt "trusty" ;;
  #  *)                 err "No support for $os_release at this time." ;;
  #esac
  install_with_yum 7
}

function configure_slave {
  if [[ ${slave_hostname+isset} ]]
  then
    mkdir -p /etc/mesos-slave
    echo "$slave_hostname" > /etc/mesos-slave/hostname
  fi
}

function install_yum_repo {
  case "$os_release" in
    # 6)           as_root rpm -Uvh http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm
    #              as_root rpm -Uvh http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm
    #              as_root yum -y install zookeeper
    #              ;;
    centos/7)      rpm -q mesosphere-el-repo || as_root rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
                   rpm -q mesos || as_root yum -y install mesos
                   rpm -q marathon || as_root yum -y install marathon
                   rpm -q mesosphere-zookeeper || as_root yum -y install mesosphere-zookeeper
                   ;;
    *)      err "No support for $os_release at this time." ;;
  esac
}

function install_with_yum {
  yum_ curl unzip
  install_yum_repo $1
  yum_ docker deimos net-tools dstat vim-enhanced mlocate
  as_root ln -sf /usr/bin/docker /usr/local/bin/docker
  #as_root sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
}

function yum_ {
  as_root env yum update -y
  as_root env yum install -y "$@"
}

function as_root {
  if [[ $(id -u) = 0 ]]
  then "$@"
  else sudo "$@"
  fi
}

function os_release {
  msg "Trying /etc/os-release..."
  if [[ -f /etc/os-release ]]
  then
    ( source /etc/os-release && display_version "$ID" "$VERSION_ID" )
    return 0
  fi
  msg "Trying /etc/redhat-release..."
  if [[ -f /etc/redhat-release ]]
  then
    # Seems to be formatted as: <distro> release <version> (<remark>)
    #                           CentOS release 6.3 (Final)
    if [[ $(cat /etc/redhat-release) =~ \
          ^(.+)' '+release' '+([^ ]+)' '+'('[^')']+')'$ ]]
    then
      local os
      case "${BASH_REMATCH[1]}" in
        'Red Hat '*) os=RedHat ;;
        *)           os="${BASH_REMATCH[1]}" ;;
      esac
      display_version "$os" "${BASH_REMATCH[2]}"
      return 0
    else
      err "/etc/redhat-release not like: <distro> release <version> (<remark>)"
    fi
  fi
  if which sw_vers &> /dev/null
  then
    local product="$(sw_vers -productName)"
    case "$product" in
      'Mac OS X') display_version MacOSX "$(sw_vers -productVersion)" ;;
      *) err "Expecting productName to be 'Mac OS X', not '$product'!";;
    esac
    return 0
  fi
  err "Could not determine OS version!"
}

function display_version {
  local os="$( tr A-Z a-z <<<"$1" )" version="$( tr A-Z a-z <<<"$2" )"
  case "$os" in
    redhat|centos|debian) out "$os/${version%%.*}" ;;   # Ignore minor versions
    macosx)               out "$os/${version%.*}" ;;  # Ignore bug fix releases
    *)                    out "$os/$version" ;;
  esac
}

function msg { out "$*" >&2 ;}
function err { local x=$? ; msg "$*" ; return $(( $x == 0 ? 1 : $x )) ;}
function out { printf '%s\n' "$*" ;}

if [[ ${1:-} ]] && declare -F | cut -d' ' -f3 | fgrep -qx -- "${1:-}"
then "$@"
else main "$@"
fi

